language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - cp src/config.development.sample.js src/config.development.js
  - npm test -- --coverage
after_script:
  #
  # Code climate configuration
  #
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info